### ISSUE TITLE
Unable to import delicious items

### ISSUE THREAD

**Issue by ntulip** [hmason/gitmarks#1]
It seems that calling delicious_import.py [username] [password] fails and calls for username and password constantly. It this has something to do with error 999 that yahoo throws.

Any work arounds?

**Comment by hmason** [comment]
I think that's an issue with Yahoo's API, so my best suggestion is just to wait and see if it happens again.

**Comment by ashearer** [comment]
If this is still happening, it would be interesting to know whether you're trying a Yahoo username and password, or an original (un-merged, pre-Yahoo) Delicious username and password.

**Comment by ntulip** [comment]
it is still happening. I have tried both my yahoo username and the original delicious username
