### ISSUE TITLE
Doesn't work on Mac OS X

### ISSUE THREAD

**Issue by ghost** [hmason/gitmarks#5]
Whenever I try doing (`gitmark` is an alias I have setup for `python gitmark.py`):

```
gitmark http://example.com
```

I get the error:

```
Traceback (most recent call last):
File "/Users/mark/src/git/gitmarks/gitmark.py", line 117, in <module>
g = gitMark(opts, args)
File "/Users/mark/src/git/gitmarks/gitmark.py", line 36, in __init__
modified.append(self.saveContent(content_filename, content))
File "/Users/mark/src/git/gitmarks/gitmark.py", line 69, in saveContent
f = open('%s%s' % (CONTENT_PATH, filename), 'w')
IOError: [Errno 2] No such file or directory:      '~/.gitmarks/content/a9b9f04336ce0181a08e774e01113b31'
```

I have the `settings.py` file setup like this:

```
TAG_PATH = '~/.gitmarks/tags/'

CONTENT_PATH = '~/.gitmarks/content/'
```

I am on Mac OS X 10.6.5

**Comment by hmason** [comment]
I'm using this on OS X.

Does the directory ~/.gitmarks/content/ exist and have writeable permissions?

**Comment by BRMatt** [comment]
Same problem on ubuntu 10.10

**Comment by ghost** [comment]
Yes, it exists and is writable.

**Comment by Heraklit** [comment]
@mrman208: 

It works for me on Mac OS X 10.6.5 after creation of subdirectories "content" and "tags" within the folder "gitmarks". Maybe your relative adresses may not be correct?

**Comment by ghost** [comment]
@Heralkit: Yes, it turns out that using `~` to refer to my home directory didn't work. So I changed it to the absolute path of my home directory (`/Users/mark`) and it works.

Thanks!
