### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by taniki** [hmason/gitmarks#7]
Wouldn't it be nicer if the content generated by gitmarks was in only one folder (with 2 sub-folders). Then it would be simple to separate the content in a different git(hub) repo with the submodule system.

Thinking about peope who want to use gitmarks and also contributing to the code.

**Comment by svetlyak40wt** [comment]
Why to bother with submodules?

I think that gitmarks should be installed separately using easy_install, pip or whatever. And then you could run it in any git repository on you choice. For example, you could have two bookmark repositories: public and private.

**Comment by taniki** [comment]
hum yeah you are right (:

then it's just lacking some documentation in order to not get mess in the branches graph
